### ISSUE TITLE
wiki setup

### ISSUE THREAD

**Issue by berquist** [shivupa/pyci#7]
We would like to start using the GitHub wiki for some minor documentation or communication, but it seems I don't have access to it? When I click on the tab, nothing happens.

**Comment by shivupa** [comment]
I created an initial page for the wiki. I'm not sure if it is now editable (by all).

**Comment by berquist** [comment]
It looks like I can't edit directly on GitHub and the command line won't let me push. This probably has something to do with repository membership. Before you change anything regarding that, let me find some official documentation on it.

**Comment by berquist** [comment]
From https://help.github.com/articles/about-github-wikis/:

> By default, only collaborators on your repository can make changes to wikis, but you can configure this to be enabled [for all users on public repositories](https://help.github.com/articles/changing-access-permissions-for-wikis).

For reference [the SymPy wiki](https://github.com/sympy/sympy/wiki) is what happens when you allow public access.

**Comment by shivupa** [comment]
Should be editable by all now.
